package models

type Session struct {
	Id                  int
	StationId           int
	LocationId          int
	UserId              int
	Email               string
	IdTag               string
	ConnectorId         int
	ConnectorOcppId     int
	ConnectorType       string
	ConnectorPower      int
	Begin               string
	End                 string
	Voltage             float64
	Current             float64
	Power               float64
	SOC                 int
	SOCBegin            int
	SOCEnd              int
	MaxPower            float64
	ChargedEnergy       float64
	PriceLimit          float64
	PricePerKwH         float64
	PercentLimit        int
	WasStartAccepted    int
	WasFirstMeterValues int
	WasStartTransaction int
	WasStopTransaction  int
	LocationCountry     string
	LocationCity        string
	LocationStreet      string
	StationSerial       string
	TotalPrice          float64
	TimeLeft            int
	LocationPhotoUrl    string
	Owner               string
}
