// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/control/control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_errorUnknown          ErrorCode = 0
	ErrorCode_errorDB               ErrorCode = 1
	ErrorCode_stationNotFound       ErrorCode = 2
	ErrorCode_sendCommandError      ErrorCode = 3
	ErrorCode_commandWasNotAccepted ErrorCode = 4
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "errorUnknown",
		1: "errorDB",
		2: "stationNotFound",
		3: "sendCommandError",
		4: "commandWasNotAccepted",
	}
	ErrorCode_value = map[string]int32{
		"errorUnknown":          0,
		"errorDB":               1,
		"stationNotFound":       2,
		"sendCommandError":      3,
		"commandWasNotAccepted": 4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_control_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_control_control_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_control_proto_rawDescGZIP(), []int{0}
}

type CustomErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomErrorDetail) Reset() {
	*x = CustomErrorDetail{}
	mi := &file_proto_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomErrorDetail) ProtoMessage() {}

func (x *CustomErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomErrorDetail.ProtoReflect.Descriptor instead.
func (*CustomErrorDetail) Descriptor() ([]byte, []int) {
	return file_proto_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *CustomErrorDetail) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CustomErrorDetail) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartStationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     int64                  `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	ConnectorId   int64                  `protobuf:"varint,2,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	SessionId     int64                  `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStationRequest) Reset() {
	*x = StartStationRequest{}
	mi := &file_proto_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStationRequest) ProtoMessage() {}

func (x *StartStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStationRequest.ProtoReflect.Descriptor instead.
func (*StartStationRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *StartStationRequest) GetStationId() int64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

func (x *StartStationRequest) GetConnectorId() int64 {
	if x != nil {
		return x.ConnectorId
	}
	return 0
}

func (x *StartStationRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type StartStationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStationResponse) Reset() {
	*x = StartStationResponse{}
	mi := &file_proto_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStationResponse) ProtoMessage() {}

func (x *StartStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStationResponse.ProtoReflect.Descriptor instead.
func (*StartStationResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *StartStationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StopStationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     int64                  `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	SessionId     int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStationRequest) Reset() {
	*x = StopStationRequest{}
	mi := &file_proto_control_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStationRequest) ProtoMessage() {}

func (x *StopStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStationRequest.ProtoReflect.Descriptor instead.
func (*StopStationRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_control_proto_rawDescGZIP(), []int{4}
}

func (x *StopStationRequest) GetStationId() int64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

func (x *StopStationRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type StopStationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStationResponse) Reset() {
	*x = StopStationResponse{}
	mi := &file_proto_control_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStationResponse) ProtoMessage() {}

func (x *StopStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStationResponse.ProtoReflect.Descriptor instead.
func (*StopStationResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_control_proto_rawDescGZIP(), []int{5}
}

func (x *StopStationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_control_control_proto protoreflect.FileDescriptor

const file_proto_control_control_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/control/control.proto\x12\acommand\"=\n" +
	"\x11CustomErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"E\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"v\n" +
	"\x13StartStationRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\x03R\tstationId\x12!\n" +
	"\fconnector_id\x18\x02 \x01(\x03R\vconnectorId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\x03R\tsessionId\"0\n" +
	"\x14StartStationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x12StopStationRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\x03R\tstationId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\"/\n" +
	"\x13StopStationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*p\n" +
	"\tErrorCode\x12\x10\n" +
	"\ferrorUnknown\x10\x00\x12\v\n" +
	"\aerrorDB\x10\x01\x12\x13\n" +
	"\x0fstationNotFound\x10\x02\x12\x14\n" +
	"\x10sendCommandError\x10\x03\x12\x19\n" +
	"\x15commandWasNotAccepted\x10\x042\x99\x01\n" +
	"\x0eControlService\x12D\n" +
	"\x05Start\x12\x1c.command.StartStationRequest\x1a\x1d.command.StartStationResponse\x12A\n" +
	"\x04Stop\x12\x1b.command.StopStationRequest\x1a\x1c.command.StopStationResponseB\vZ\t.;controlb\x06proto3"

var (
	file_proto_control_control_proto_rawDescOnce sync.Once
	file_proto_control_control_proto_rawDescData []byte
)

func file_proto_control_control_proto_rawDescGZIP() []byte {
	file_proto_control_control_proto_rawDescOnce.Do(func() {
		file_proto_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_control_proto_rawDesc), len(file_proto_control_control_proto_rawDesc)))
	})
	return file_proto_control_control_proto_rawDescData
}

var file_proto_control_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_control_control_proto_goTypes = []any{
	(ErrorCode)(0),               // 0: command.ErrorCode
	(*CustomErrorDetail)(nil),    // 1: command.CustomErrorDetail
	(*CommandResponse)(nil),      // 2: command.CommandResponse
	(*StartStationRequest)(nil),  // 3: command.StartStationRequest
	(*StartStationResponse)(nil), // 4: command.StartStationResponse
	(*StopStationRequest)(nil),   // 5: command.StopStationRequest
	(*StopStationResponse)(nil),  // 6: command.StopStationResponse
}
var file_proto_control_control_proto_depIdxs = []int32{
	3, // 0: command.ControlService.Start:input_type -> command.StartStationRequest
	5, // 1: command.ControlService.Stop:input_type -> command.StopStationRequest
	4, // 2: command.ControlService.Start:output_type -> command.StartStationResponse
	6, // 3: command.ControlService.Stop:output_type -> command.StopStationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_control_control_proto_init() }
func file_proto_control_control_proto_init() {
	if File_proto_control_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_control_proto_rawDesc), len(file_proto_control_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_control_proto_goTypes,
		DependencyIndexes: file_proto_control_control_proto_depIdxs,
		EnumInfos:         file_proto_control_control_proto_enumTypes,
		MessageInfos:      file_proto_control_control_proto_msgTypes,
	}.Build()
	File_proto_control_control_proto = out.File
	file_proto_control_control_proto_goTypes = nil
	file_proto_control_control_proto_depIdxs = nil
}
