// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/control/control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_internal_proto_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartStationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStationRequest) Reset() {
	*x = StartStationRequest{}
	mi := &file_internal_proto_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStationRequest) ProtoMessage() {}

func (x *StartStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStationRequest.ProtoReflect.Descriptor instead.
func (*StartStationRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *StartStationRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

type StartStationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStationResponse) Reset() {
	*x = StartStationResponse{}
	mi := &file_internal_proto_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStationResponse) ProtoMessage() {}

func (x *StartStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStationResponse.ProtoReflect.Descriptor instead.
func (*StartStationResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *StartStationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StopStationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStationRequest) Reset() {
	*x = StopStationRequest{}
	mi := &file_internal_proto_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStationRequest) ProtoMessage() {}

func (x *StopStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStationRequest.ProtoReflect.Descriptor instead.
func (*StopStationRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *StopStationRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

type StopStationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStationResponse) Reset() {
	*x = StopStationResponse{}
	mi := &file_internal_proto_control_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStationResponse) ProtoMessage() {}

func (x *StopStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_control_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStationResponse.ProtoReflect.Descriptor instead.
func (*StopStationResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_control_control_proto_rawDescGZIP(), []int{4}
}

func (x *StopStationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_proto_control_control_proto protoreflect.FileDescriptor

const file_internal_proto_control_control_proto_rawDesc = "" +
	"\n" +
	"$internal/proto/control/control.proto\x12\acommand\"E\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x13StartStationRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\"0\n" +
	"\x14StartStationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x12StopStationRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\"/\n" +
	"\x13StopStationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x99\x01\n" +
	"\x0eCommandService\x12D\n" +
	"\x05Start\x12\x1c.command.StartStationRequest\x1a\x1d.command.StartStationResponse\x12A\n" +
	"\x04Stop\x12\x1b.command.StopStationRequest\x1a\x1c.command.StopStationResponseB\bZ\x06.;userb\x06proto3"

var (
	file_internal_proto_control_control_proto_rawDescOnce sync.Once
	file_internal_proto_control_control_proto_rawDescData []byte
)

func file_internal_proto_control_control_proto_rawDescGZIP() []byte {
	file_internal_proto_control_control_proto_rawDescOnce.Do(func() {
		file_internal_proto_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_control_control_proto_rawDesc), len(file_internal_proto_control_control_proto_rawDesc)))
	})
	return file_internal_proto_control_control_proto_rawDescData
}

var file_internal_proto_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_control_control_proto_goTypes = []any{
	(*CommandResponse)(nil),      // 0: command.CommandResponse
	(*StartStationRequest)(nil),  // 1: command.StartStationRequest
	(*StartStationResponse)(nil), // 2: command.StartStationResponse
	(*StopStationRequest)(nil),   // 3: command.StopStationRequest
	(*StopStationResponse)(nil),  // 4: command.StopStationResponse
}
var file_internal_proto_control_control_proto_depIdxs = []int32{
	1, // 0: command.CommandService.Start:input_type -> command.StartStationRequest
	3, // 1: command.CommandService.Stop:input_type -> command.StopStationRequest
	2, // 2: command.CommandService.Start:output_type -> command.StartStationResponse
	4, // 3: command.CommandService.Stop:output_type -> command.StopStationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_control_control_proto_init() }
func file_internal_proto_control_control_proto_init() {
	if File_internal_proto_control_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_control_control_proto_rawDesc), len(file_internal_proto_control_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_control_control_proto_goTypes,
		DependencyIndexes: file_internal_proto_control_control_proto_depIdxs,
		MessageInfos:      file_internal_proto_control_control_proto_msgTypes,
	}.Build()
	File_internal_proto_control_control_proto = out.File
	file_internal_proto_control_control_proto_goTypes = nil
	file_internal_proto_control_control_proto_depIdxs = nil
}
